workflows:
  ios_only:
    name: Cold Bore - iOS (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    # Use the App Store Connect API key you added in Codemagic UI
    integrations:
      app_store_connect: Codemagic CI

    environment:
      flutter: stable

      # Enable automatic fetching of signing files for TestFlight/App Store.
      # (Requires that iOS signing is enabled for this app in Codemagic UI.)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.remington.coldbore

    scripts:
      - name: Pub get
        script: flutter pub get

      - name: Analyze
        script: flutter analyze

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build iOS IPA (Release)
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/*.txt

    publishing:
      app_store_connect:
        # Use the App Store Connect API key from the 'integrations' section above
        auth: integration

        # Upload to TestFlight
        submit_to_testflight: true
