workflows:
  ios_testflight:
    name: Cold Bore - iOS (TestFlight)

    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Cold Bore API

    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.remington.coldbore

    scripts:
      - name: Pub get
        script: flutter pub get

      - name: Analyze (non-blocking)
        script: flutter analyze || true

      - name: Apply iOS signing settings
        script: xcode-project use-profiles

      - name: Build IPA (Release)
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist


    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
