workflows:
  ios_only:
    name: Cold Bore - iOS build (no signing yet)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Pub get
        script: flutter pub get

      - name: Analyze
        script: flutter analyze

      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/**/outputs/**/*.txt
